language: python

python:
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.6

install:
  - pip install -q Django==$DJANGO
  - pip install -r pip-requirements.txt --use-mirrors
  - python manage.py collectstatic --noinput -l

script:
  - python manage.py test exeapp check_media strict_filebrowser --settings=test_settings
