language: python

python:
  - "2.7"

env:
  - DJANGO=1.5.1

install:
  - pip install -q Django==$DJANGO
  - pip install -r src/exedjango/pip_requirements.txt --use-mirrors

script:
  - python src/exedjango/manage.py test exeapp check_media strict_filebrowser
